app/company/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateTimeField, FileField, TextAreaField
from wtforms.validators import DataRequired, Length, Email


class RegisterCompanyForm(FlaskForm):
    name = StringField('Firm Name', render_kw={"placeholder": "Firm Name"},
                       validators=[DataRequired(), Length(1, 64)])
    manager = StringField('Manager', render_kw={"placeholder": "Manager"},
                          validators=[DataRequired(), Length(1, 64)])
    email = StringField('Firm Email', render_kw={"placeholder": "Firm Email"},
                        validators=[DataRequired(), Length(1, 64), Email()])
    phone = StringField('Phone Number', render_kw={"placeholder": "Phone Number"},
                        validators=[DataRequired(), Length(1, 64)])
    submit = SubmitField('Submit')


class PublishActivityForm(FlaskForm):
    name = StringField('Activity Name', render_kw={"placeholder": "Activity Name"},
                       validators=[DataRequired(), Length(1, 64)])
    time = DateTimeField("Activity Time", validators=[DataRequired()], format='%Y-%m-%dT%H:%M')
    place = StringField('Activity Place', render_kw={"placeholder": "Activity Place"}, validators=[DataRequired()])
    describe = TextAreaField('Activity Describe', render_kw={"placeholder": "Activity Describe"},
                             validators=[DataRequired()])
    organizer = StringField('Activity Organizer', render_kw={"placeholder": "Activity Organizer"},
                            validators=[DataRequired()])
    photo = FileField('Auto Show', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/company/__init__.py
from flask import Blueprint

company = Blueprint('company', __name__)

from . import views

app/company/views.py
import base64

from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
import datetime
from . import company
from .. import db
from ..decorators import permission_required
from ..models import Company, User, Activity, Permission
from ..email import send_email
from .forms import RegisterCompanyForm, PublishActivityForm
from .cloud import *

@company.route('/register', methods=['GET', 'POST'])
def register_company():
    form = RegisterCompanyForm()
    if form.validate_on_submit():
        email_find = User.query.filter_by(email=form.email.data).first()
        if email_find is not None:
            flash("Your email has been registered, please change your email")
            return render_template('company/company_register.html', form=form)
        username_find = User.query.filter_by(username=form.name.data).first()
        if username_find is not None:
            flash("Your company name has been registered, please change your username")
            return render_template('company/company_register.html', form=form)
        company = Company(name=form.name.data,
                          phone=form.phone.data,
                          email=form.email.data,
                          manager=form.manager.data)
        db.session.add(company)
        db.session.commit()
        try:
            register_company_cloud(0, form.name.data, form.manager.data, form.phone.data, form.email.data)
        except:
            pass
        token = company.generate_confirmation_token()
        send_email('1360412598@qq.com', 'Register Firm',
                   'mail_company/To_administrator', company=company, token=token)
        flash('A register firm-account email has been sent to administrator.')
        return redirect(url_for('auth.login'))
    return render_template('company/company_register.html', form=form)


@company.route('/send_result/<oid>', methods=['GET', 'POST'])
def send_result(oid):
    return render_template('company/send_result.html', oid=oid)


@company.route('/register_success/<oid>', methods=['GET'])
def register_success(oid):
    firm = Company.query.filter_by(id=oid).first()
    manager = User.query.filter_by(username=firm.manager).first()
    manager.role_id = 2
    db.session.add(manager)
    db.session.commit()
    try:
        register_successful_cloud(oid)
    except:
        pass
    # 注册时发送邮箱认证
    token = firm.generate_confirmation_token()
    send_email(firm.email, 'Register Company Success',
               'mail_company/success_register', user=manager, token=token, firm=firm)
    flash('A register_success email has been sent to company by email.')
    return redirect(url_for('auth.login'))


@company.route('/register_fail/<oid>', methods=['GET'])
def result_fail(oid):
    firm = Company.query.filter_by(id=oid).first()
    token = firm.generate_confirmation_token()
    send_email(firm.email, 'Register Company Fail',
               'mail_company/fail_register', token=token)
    flash('A register_fail email has been sent to company by email.')
    return redirect(url_for('auth.login'))


@company.route('/new_activity', methods=['GET', 'POST'])
def company_activity():
    form = PublishActivityForm()
    if form.validate_on_submit():
        str_time = form.time.data
        name = form.name.data
        place = form.place.data
        describe = form.describe.data
        organizer = form.organizer.data
        if name == "" or place == "" or str_time == "" or describe == "" or organizer == "":
            flash("Activity information cannot be empty")
            return render_template('company/new_activity.html')
        img = form.photo.data.read()
        img_bytes = base64.b64encode(img)
        img_bytes = str(img_bytes, 'utf-8')
        acti = Activity(activity_name=name,
                        activity_time=str_time,
                        activity_place=place,
                        activity_describe=describe,
                        Organizer=organizer,
                        announcer_id=current_user.id,
                        photo=img_bytes
                        )
        db.session.add(acti)
        db.session.commit()
        try:
            new_activity_cloud(name, datetime.datetime.strftime(str_time, '%Y-%m-%d %H:%M:%S'), place, describe, organizer, current_user.id)
        except:
            pass
        flash('Your Activity Announcement has been released!')
        return redirect(url_for('main.index_activity'))
    return render_template('company/new_activity.html', form=form)


@company.route('/want/<activity_id>')
@login_required
@permission_required(Permission.FOLLOW)
def want(activity_id):
    activity = Activity.query.filter_by(id=activity_id).first()
    if activity is None:
        flash('Invalid activity.')
        return redirect(url_for('main.index_activity'))
    if current_user.is_wanting(activity):
        flash('You are already wanting this post.')
        return redirect(url_for('main.index_activity'))
    current_user.want(activity)
    activity.want(current_user)
    db.session.commit()
    try:
        new_want_cloud(current_user.id, activity.id, datetime.datetime.strftime(activity.timestamp, '%Y-%m-%d %H:%M:%S'))
    except:
        pass
    flash('You are now wanting this post')
    return redirect(url_for('main.index_activity'))


@company.route('/not_want/<activity_id>')
@login_required
@permission_required(Permission.FOLLOW)
def not_want(activity_id):
    activity = Activity.query.filter_by(id=activity_id).first()
    if activity is None:
        flash('Invalid activity.')
        return redirect(url_for('main.index_activity'))
    if not current_user.is_wanting(activity):
        flash('You are not wanting this post.')
        return redirect(url_for('main.index_activity'))
    current_user.not_want(activity)
    activity.not_want(current_user)
    db.session.commit()
    try:
        not_want_cloud(current_user.id)
    except:
        pass
    flash('You are not wanting this post')
    return redirect(url_for('main.index_activity'))


@company.route('/delete_transaction/<int:activity_id>')
@login_required
def delete_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    if current_user == activity.announcer:
        db.session.delete(activity)
        db.session.commit()
        try:
            delete_activity_cloud(activity_id)
        except:
            pass
        # flash('你没有删评论权限')
        flash('The activity has been deleted.')
        return redirect(url_for('main.user', username=activity.announcer.username))
    else:
        flash('你没有删评论权限')
        return redirect(url_for('main.user', username=activity.announcer.username))

app/templates/company/_activities.html
<li class="avtivity" id="{{  activity.id }}">
    <div class="panel panel-warning">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <h3 class="item-name" style="display: inline">
                {{ activity.activity_name }}
            </h3>
            {% if activity.is_invalid %}
                <h2 style="display: inline; float: right">The event has expired!</h2>
            {% endif %}
        </div>
        <div class="panel-body">
            <p><strong>Details:</strong>{{ activity.activity_describe }}</p>
        </div>
        <!-- List group -->
        <ul class="list-group">
            <li class="list-group-item"><strong>Time</strong> {{ activity.activity_time }}</li>
            <li class="list-group-item"><strong>Place</strong> {{ activity.activity_place }}</li>
            <li class="list-group-item"><strong>Organizer:</strong> {{ activity.Organizer }}</li>
            {% if activity.photo %}
            <li class="list-group-item"><strong>Auto Show</strong>
                <img src="data:image/png;base64,{{ activity.photo }}" height="180px" width="350px"/>
            </li>
            {% endif %}
        </ul>

        <div class="panel-footer">
             <a class="head-photo" href="{{ url_for('.user', username=activity.announcer.username) }}">
                 {% if activity.announcer.avatar_img %}
                     <img class="img-rounded profile-thumbnail" src="{{ activity.announcer.avatar_img }}" alt="avatar"  style="width: 25px; height: 25px">
                 {% else %}
                     <img class="img-rounded profile-thumbnail" src="{{ activity.announcer.gravatar(size=25) }}" alt="avatar">
                 {% endif %}
            </a>
            <span class="post-author">
                <a href="{{ url_for('.user', username=activity.announcer.username) }}">
                    {{ activity.announcer.username }}
                    {% if activity.announcer.can(Permission.ACTIVITY) %}
                        <svg class="icon" viewBox="0 0 1024 1024" width="14" height="14" style="margin: 0;">
                            <path d="M959.786667 148.906667l-44.330667-0.725333c-1.024 0-100.437333-2.048-203.050667-41.728-105.301333-40.789333-173.141333-87.552-173.781333-88.021333L511.872 0 485.248 18.474667C484.608 18.901333 416.768 65.706667 311.466667 106.453333 208.938667 146.218667 109.482667 148.181333 108.544 148.181333L64 148.906667l0 430.464C64 795.477333 355.328 1024 511.957333 1024 668.714667 1024 960 795.477333 960 579.370667L959.786667 148.906667zM321.877333 772.48 321.877333 355.413333 282.112 355.413333 282.112 317.482667 441.173333 317.482667l0 189.610667 200.192-189.610667 157.696 0L321.877333 772.48z" fill="#3688FF"></path>
                        </svg>
                    {% endif %}
                </a>
            </span>
            <span class="post-date">{{ moment(activity.timestamp).fromNow() }}</span>

            {% if not current_user.is_wanting(activity) %}
                <a class="icon-btn" style="float:right; margin-right: 15px" href="{{ url_for('company.want', activity_id=activity.id) }}#{{ activity.id }}">
                    <span class="glyphicon glyphicon-heart-empty"></span>
                    <span>{{ activity.wanter.count() }} WantToGo</span>
                </a>
            {% else %}
                <a class="icon-btn" style="float:right; margin-right: 15px" href="{{ url_for('company.not_want', activity_id=activity.id) }}#{{ activity.id }}">
                    <span class="glyphicon glyphicon-heart"></span>
                    <span>{{ activity.wanter.count() }} WantToGo</span>
                </a>
            {% endif %}
        </div>
    </div>
</li>

app/templates/company/_activitiesInProfile.html
<ul class="posts list-unstyled">
    {% for activity in activities %}
    <li class="avtivity" id="{{  activity.id }}">
        <div class="col-md-12">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <h3 class="item-name" style="display: inline">
                        {{ activity.activity_name }}
                    </h3>
                </div>
                <div class="panel-body">
                    <p><strong>Details:</strong>{{ activity.activity_describe }}</p>
                </div>
                <!-- List group -->
                <ul class="list-group">
                    <li class="list-group-item"><strong>Time</strong> {{ activity.activity_time }}</li>
                    <li class="list-group-item"><strong>Place</strong> {{ activity.activity_place }}</li>
                    <li class="list-group-item"><strong>Organizer:</strong> {{ activity.Organizer }}</li>
                    {% if activity.photo %}
                    <li class="list-group-item"><strong>Auto Show</strong>
                        <img src="data:image/png;base64,{{ activity.photo }}" height="180px" width="350px"/>
                    </li>
                    {% endif %}
                </ul>

                <div class="panel-footer">
                    <span class="post-date">{{ moment(activity.timestamp).fromNow() }}</span>

                    {# 删除#}
                    {% if current_user == activity.announcer %}
                    <a class="icon-btn" href="{{ url_for('company.delete_activity', activity_id=activity.id)}}">
                        <span class="glyphicon glyphicon-trash"></span>
                        <span>delete</span>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/company/_activitiesWantingInProfile.html
<li class="avtivity" id="{{  want.wanted_Activity.id }}">
    <div class="panel panel-warning">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <h3 class="item-name" style="display: inline">
                {{ want.wanted_Activity.activity_name }}
            </h3>
            {% if want.wanted_Activity.is_invalid %}
            <h2 style="display: inline; float: right">The event has expired!</h2>
            {% endif %}
        </div>
        <div class="panel-body">
            <p><strong>Details:</strong>{{ want.wanted_Activity.activity_describe }}</p>
        </div>
        <!-- List group -->
        <ul class="list-group">
            <li class="list-group-item"><strong>Time</strong> {{ want.wanted_Activity.activity_time }}</li>
            <li class="list-group-item"><strong>Place</strong> {{ want.wanted_Activity.activity_place }}</li>
            <li class="list-group-item"><strong>Organizer:</strong> {{ want.wanted_Activity.Organizer }}</li>
            {% if want.wanted_Activity.photo %}
            <li class="list-group-item"><strong>Auto Show</strong>
                <img src="data:image/png;base64,{{ want.wanted_Activity.photo }}" height="180px" width="350px"/>
            </li>
            {% endif %}
        </ul>

        <div class="panel-footer">
            <a class="head-photo" href="{{ url_for('.user', username=want.wanted_Activity.announcer.username) }}">
                {% if want.wanted_Activity.announcer.avatar_img %}
                <img class="img-rounded profile-thumbnail" src="{{ want.wanted_Activity.announcer.avatar_img }}"
                     alt="avatar" style="width: 25px; height: 25px">
                {% else %}
                <img class="img-rounded profile-thumbnail" src="{{ want.wanted_Activity.announcer.gravatar(size=25) }}"
                     alt="avatar">
                {% endif %}
            </a>
            <span class="post-author">
                <a href="{{ url_for('.user', username=want.wanted_Activity.announcer.username) }}">
                    {{ want.wanted_Activity.announcer.username }}
                    {% if want.wanted_Activity.announcer.can(Permission.ACTIVITY) %}
                        <svg class="icon" viewBox="0 0 1024 1024" width="16" height="16" style="margin: 0">
                            <path d="M959.786667 148.906667l-44.330667-0.725333c-1.024 0-100.437333-2.048-203.050667-41.728-105.301333-40.789333-173.141333-87.552-173.781333-88.021333L511.872 0 485.248 18.474667C484.608 18.901333 416.768 65.706667 311.466667 106.453333 208.938667 146.218667 109.482667 148.181333 108.544 148.181333L64 148.906667l0 430.464C64 795.477333 355.328 1024 511.957333 1024 668.714667 1024 960 795.477333 960 579.370667L959.786667 148.906667zM321.877333 772.48 321.877333 355.413333 282.112 355.413333 282.112 317.482667 441.173333 317.482667l0 189.610667 200.192-189.610667 157.696 0L321.877333 772.48z"
                                  fill="#3688FF"></path>
                        </svg>
                    {% endif %}
                </a>
            </span>

            <span class="date" style="float: right">
                <span class="glyphicon glyphicon-time"></span>
                {{ moment(want.wanted_Activity.timestamp).fromNow() }}
            </span>
        </div>
    </div>
</li>

app/templates/company/company_register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}Company Register{% endblock %}


{% block head %}
{{ super() }}
    <!-- 新 Bootstrap 核心 CSS 文件 -->
    <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static',filename='signin.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='bg.css') }}" rel="stylesheet">
{% endblock %}


{% block body %}

<div class="onepage">
        <div class = "onepage-bg" id = "onepagebg">

{#        导航栏#}
            <nav calss="navbar navbar-inverse bg-light " role="navigation" style="background-color: rgba(245,245,245,0.7);">
                <div class="container">
{#                    头部#}
                    <div class="navbar-header">
                        <button type="button" class=" btn-warning navbar-toggle " data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" class="navbar-brand">Automobile Nation</a>
                    </div>

{#                    尾部#}
                    <div class="collapse navbar-collapse">

                        <div class="nav navbar-nav navbar-right">
                            <li class="chose">
                                 <a class="btn ref-signup chose" href="/auth/register">
                                 Register
                                 </a>
                             </li>
                        </div>

                        <div class="nav navbar-nav navbar-right">
                            <li class="chose">
                                <a  class="btn ref-signup chose" href="/auth/login">
                                    Signin
                                </a>
                            </li>
                        </div>

                    </div>

                </div>
            </nav>


            <div class="container">

                <!--    flash消息显示区-->
                {% for message in get_flashed_messages() %}
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-8 alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                    <div class="col-sm-2">
                    </div>
                {% endfor %}

                <form role="form" class="form-signin" method="post" style="margin: 120px auto 0px auto;">
                    <h2 class="form-signin-heading">Company Register</h2>

                    {{ form.csrf_token }}
                    {{ form.name (id="name")}}
                    {{ form.manager (id="manager")}}
                    {{ form.email (id="email")}}
                    {{ form.phone (id="phone")}}
                    <p id="p1"></p>
                    {{ form.submit (id="submit")}}
                </form>
            </div>
        </div>
</div>


<script>
        // 只要有id就能改
        document.getElementById('name').className = 'form-control'
        document.getElementById('manager').className = 'form-control'
        document.getElementById('email').className = 'form-control'
        document.getElementById('phone').className = 'form-control'

        var submit = document.getElementById('submit')
        submit.className = 'btn btn-lg btn-warning btn-block chose';
</script>



{% endblock %}

app/templates/company/new_activity.html
{% extends "base.html" %}


{% block title %}New Company Activity{% endblock %}


{% block head %}
{{ super() }}
<!--     Custom styles for this template -->
<link href="{{ url_for('static',filename='new-activity.css') }}" rel="stylesheet">
{% endblock %}


{% block page_content %}


<div class="container">
    <div class="col-md-12">

        <!--        左侧表单-->
        <div class="col-md-6">
            <form class="form-activity form-horizontal" method="post" enctype="multipart/form-data">
                {{ form.csrf_token }}
                <h1 class="form-activity-heading col-sm-offset-1">Auto Show</h1>
                <!--                    活动名称-->
                <div class="form-group">
                    {{ form.name.label (for="activity_name", class="col-sm-offset-1 col-sm-3") }}
                    <div class="col-sm-8">
                        {{ form.name(id="activity_name", type="text", class="form-control")}}
                    </div>
                    {% for error in form.name.errors %}
                    <span style="color:red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <!--                    活动时间-->
                <div class="form-group">
                    {{ form.time.label(for="activity_time", class="col-sm-offset-1 col-sm-3") }}
                    <div class="col-sm-8">
                        {{ form.time(id="activity_time", type="datetime-local", class="form-control") }}
                    </div>
                    {% for error in form.time.errors %}
                    <span style="color:red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <!--                    活动地点-->
                <div class="form-group">
                    {{ form.place.label(for="activity_place", class="col-sm-offset-1 col-sm-3") }}
                    <div class="col-sm-8">
                        {{ form.place(id="activity_place", type="text", class="form-control") }}
                    </div>
                    {% for error in form.place.errors %}
                    <span style="color:red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <!--                    活动描述-->
                <div class="form-group">
                    {{ form.describe.label(for="activity_describe", class="col-sm-offset-1 col-sm-3") }}
                    <div class="col-sm-8">
                        {{form.describe(id="activity_describe", class="form-control describe", rows="3")}}
                    </div>
                    {% for error in form.describe.errors %}
                    <span style="color:red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <!--                    组织者-->
                <div class="form-group">
                    {{ form.organizer.label(for="organizer", class="col-sm-offset-1 col-sm-3") }}
                    <div class="col-sm-8">
                        {{ form.organizer(id="organizer", type="text", class="form-control") }}
                    </div>
                    {% for error in form.organizer.errors %}
                    <span style="color:red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <!--                    是否获批-->
                <div class="form-group">
                    {{ form.photo.label(for="photo", class="col-sm-offset-1 col-sm-3") }}
                    <div class="col-sm-8">
                        {{ form.photo(id="photo", class="form-control") }}
                    </div>
                    {% for error in form.photo.errors %}
                    <span style="color:red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <!--                    提交表单-->
                <div class="col-sm-offset-4 col-sm-7">
                    {{ form.submit(class="btn btn-success active-submit", id="submit") }}
                </div>
            </form>
        </div>

        <!--        右侧图片-->
        <div class="col-md-6 decorate-photo">
        </div>
    </div>
</div>

{% endblock %}

app/templates/company/send_result.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}Send Register Result{% endblock %}


{% block head %}
{{ super() }}
    <!-- 新 Bootstrap 核心 CSS 文件 -->
    <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static',filename='signin.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='bg.css') }}" rel="stylesheet">
{% endblock %}


{% block body %}

<div class="onepage">
        <div class = "onepage-bg" id = "onepagebg">

            <nav calss="navbar navbar-inverse bg-light " role="navigation" style="background-color: rgba(245,245,245,0.7);">
                <div class="container">
{#                    头部#}
                    <div class="navbar-header">
                        <button type="button" class=" btn-warning navbar-toggle " data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" class="navbar-brand">Automobile Nation</a>
                    </div>

{#                    尾部#}
                    <div class="collapse navbar-collapse">

                        <div class="nav navbar-nav navbar-right">
                            <li class="chose">
                                 <a class="btn ref-signup chose" href="/auth/register">
                                 Register
                                 </a>
                             </li>
                        </div>

                        <div class="nav navbar-nav navbar-right">
                            <li class="chose">
                                <a  class="btn ref-signup chose" href="/auth/login">
                                    Signin
                                </a>
                            </li>
                        </div>

                    </div>

                </div>
            </nav>


            <div class="container">

                <!--    flash消息显示区-->
                {% for message in get_flashed_messages() %}
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-8 alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                    <div class="col-sm-2">
                    </div>
                {% endfor %}

                <form role="form" class="form-signin" method="post" style="margin: 120px auto 0px auto;">
                    <h2 class="form-signin-heading">Send Result Email</h2>
                    <a class="btn btn-lg btn-warning btn-block chose" href="{{ url_for('company.register_success', oid=oid) }}">Register Success</a>
                    <a class="btn btn-lg btn-warning btn-block chose" href="{{ url_for('company.result_fail', oid=oid) }}">Register Fail</a>
                </form>
            </div>
        </div>
</div>
{% endblock %}